[project]
name = "microbiome-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "dice-ml>=0.9",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "ruff>=0.11.6",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[project.scripts]
microbiome-ml = "microbiome_ml.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/microbiome_ml"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
